
[[commands]]
modifiers = { alt = true, shift = true, control = true }
hotkey = "KeyT"
script = "PowerShell -Command \"Add-Type -AssemblyName PresentationFramework;[System.Windows.MessageBox]::Show('Daemon Running')\""

[[commands]]
modifiers = { alt = true, shift = true, control = true }
hotkey = "KeyS"
script = "firefox -private-window https://hurawatch.bz/tv/south-park-j2ywy/"

[[commands]]
modifiers = { alt = true, shift = true, control = true }
hotkey = "KeyK"
script = "C:/Development/local/bin/debt_manager/debt_manager.exe"